"""
Radiation-pressure (ponderomotive) back-action on the single-mode sensing channel.

Extends :mod:`dynamics` with the linearised opto-mechanical
back-action of a free-mass interferometer at one sideband frequency, keeping the
noise-stage structure, the unit conversions and the QuTiP types of the existing
package.

Physics
-------
In the two-photon (Caves--Schumaker / Kimble) formalism the lossless free-mass
input--output relation at sideband frequency :math:`\\Omega` is

.. math::
    b_1 = a_1, \\qquad b_2 = a_2 - \\kappa a_1 + \\sqrt{2\\kappa}\\, h/h_{\\rm SQL},

with the overall propagation phase dropped.  Writing
:math:`x = (a + a^\\dagger)/\\sqrt2` and :math:`p = (a - a^\\dagger)/(i\\sqrt2)`,
so that :math:`a_1 = \\sqrt2\\,x` and :math:`a_2 = \\sqrt2\\,p`, this is

.. math::   x \\to x, \\qquad p \\to p - \\kappa x + \\lambda .

Back-action is therefore a **shear** in phase space,
:math:`S(\\kappa) = \\begin{pmatrix}1 & 0\\\\ -\\kappa & 1\\end{pmatrix}`,
generated by

.. math::   U_{\\rm BA}(\\kappa) = \\exp\\!\\left(-\\tfrac{i}{2}\\kappa\\,\\hat x^2\\right)
            = \\exp\\!\\left(-\\tfrac{i}{4}\\kappa\\,(a + a^\\dagger)^2\\right),

which is equivalently a squeeze plus a rotation with
:math:`e^{r} - e^{-r} = \\kappa` (see :func:`shear_as_squeeze_rotation`).

Relation to the existing sensing Hamiltonian
--------------------------------------------
:func:`dynamics.get_state_single_mode` uses

.. math::   H = \\Delta\\,\\hat n + \\epsilon_a (a^\\dagger + a) + i\\,\\epsilon_p (a^\\dagger - a),

so with :math:`(a^\\dagger + a) = \\sqrt2\\,\\hat x` and
:math:`i(a^\\dagger - a) = \\sqrt2\\,\\hat p`:

* ``epsilon_a`` drives the generator :math:`\\sqrt2\\,\\hat x` and hence
  **displaces p** -- this is the gravitational-wave signal quadrature, and it is
  the parameter to estimate in every back-action study here;
* ``epsilon_p`` drives :math:`\\sqrt2\\,\\hat p` and displaces :math:`x`.

Because ``epsilon_a`` and the back-action generator are both functions of
:math:`\\hat x` they **commute**, so in the physical configuration the three
orderings BA1, BA2 and BA3 coincide exactly.  They separate only for
``epsilon_p`` (or a general quadrature angle), where BA3 lies between BA1 and
BA2.  Both cases are exercised by the test-suite.

Channel orderings
-----------------
``"none"``  signal only, no radiation pressure (reference)
``"BA1"``   radiation pressure -> displacement sensing
``"BA2"``   displacement sensing -> radiation pressure
``"BA3"``   simultaneous, the physical case

Loss and phase noise keep the three-stage placement of the existing package:
``eta_in``/``pn_in`` act before the opto-mechanical interaction (injection loss,
input phase noise) and ``eta_out``/``pn_out`` after it (detection loss, output
phase noise).  ``eta_ch``/``pn_ch`` act *during* it, alongside the Hamiltonian.
"""

from functools import lru_cache

import numpy as np
import qutip as qt
from scipy.linalg import expm
from scipy.special import gammaln

from conversions import loss_to_kappa, phirms_to_chi

__all__ = [
    "ORDERINGS",
    "SOLVERS",
    "x_quadrature",
    "p_quadrature",
    "backaction_hamiltonian",
    "backaction_unitary",
    "shear_as_squeeze_rotation",
    "suggested_cutoff",
    "get_state_single_mode_ba",
]

ORDERINGS = ("none", "BA1", "BA2", "BA3")

#: ``"exact"`` uses closed-form maps; ``"mesolve"`` uses the QuTiP integrator that
#: :mod:`dynamics` uses.  They implement the same channel -- see
#: ``test_exact_and_mesolve_solvers_agree`` -- but "exact" is orders of magnitude
#: faster at the cutoffs radiation pressure needs, where the integrator has to
#: propagate an N^2-dimensional Liouvillian.
SOLVERS = ("exact", "mesolve")

# QuTiP solver tolerances.  The package default (atol 1e-8, rtol 1e-6) limits QFI
# accuracy to ~1e-4 relative for near-pure states, which is coarser than the
# effects studied here; these were checked against a closed-form Gaussian result.
_SOLVER_OPTIONS = {"atol": 1e-12, "rtol": 1e-10, "nsteps": 100000}


def x_quadrature(N_basis):
    r""":math:`\hat x = (a + a^\dagger)/\sqrt2`, vacuum variance 1/2."""
    a = qt.destroy(N_basis)
    return (a + a.dag()) / np.sqrt(2)


def p_quadrature(N_basis):
    r""":math:`\hat p = (a - a^\dagger)/(i\sqrt2)`, vacuum variance 1/2."""
    a = qt.destroy(N_basis)
    return (a - a.dag()) / (1j * np.sqrt(2))


def backaction_hamiltonian(N_basis, kappa, t_final=1.0):
    r"""Hamiltonian whose action over ``t_final`` is the shear :math:`e^{-i\kappa x^2/2}`.

    Returns :math:`H_{\rm BA} = \kappa\,\hat x^2 / (2\,t_{\rm final})`, so that
    :math:`\int_0^{t_{\rm final}} H_{\rm BA}\,dt = \kappa \hat x^2/2` regardless
    of the integration time.  Used for the simultaneous ("BA3") ordering, where
    it is added to the sensing Hamiltonian.
    """
    x = x_quadrature(N_basis)
    return (float(kappa) / (2.0 * float(t_final))) * (x * x)


@lru_cache(maxsize=128)
def _backaction_unitary_cached(N_basis, kappa):
    vals, vecs = _x_eig(N_basis)
    return (vecs * np.exp(-0.5j * kappa * vals**2)) @ vecs.conj().T


def backaction_unitary(N_basis, kappa):
    r"""Ponderomotive unitary :math:`U_{\rm BA} = \exp(-i\kappa \hat x^2/2)`.

    In the Heisenberg picture this implements :math:`x \to x`,
    :math:`p \to p - \kappa x`.

    The exponential is built from the eigendecomposition of :math:`\hat x`
    rather than a dense matrix exponential: every unitary generated by a
    function of a single quadrature is diagonal in that basis, and the cutoffs
    the shear demands (hundreds of levels) make ``expm`` needlessly expensive.
    """
    kappa = float(kappa)
    if kappa == 0.0:
        return qt.qeye(N_basis)
    return qt.Qobj(_backaction_unitary_cached(N_basis, kappa))


def shear_as_squeeze_rotation(kappa):
    r"""Decompose the shear into rotation - squeeze - rotation.

    Returns ``(r, theta_pre, theta_post)`` with

    .. math:: S(\kappa) = R(\theta_{\rm post})\,\mathrm{diag}(e^{r}, e^{-r})\,R(\theta_{\rm pre}),

    i.e. the "linearised ponderomotive form: squeezing plus rotation".  The
    squeeze factor obeys :math:`e^{r} - e^{-r} = \kappa`.
    """
    kappa = float(kappa)
    S = np.array([[1.0, 0.0], [-kappa, 1.0]])
    u, sv, vh = np.linalg.svd(S)
    if np.linalg.det(u) < 0:
        u[:, 1] *= -1
        vh[1, :] *= -1
    return float(np.log(sv[0])), float(np.arctan2(vh[1, 0], vh[0, 0])), float(np.arctan2(u[1, 0], u[0, 0]))


def suggested_cutoff(nbar, kappa, safety=8.0):
    r"""Rule-of-thumb Fock cutoff for a probe of mean photon number ``nbar`` under shear ``kappa``.

    The shear multiplies the :math:`p` variance by up to :math:`1 + \kappa^2`, so
    the output photon number grows roughly like
    :math:`(1 + \kappa^2)(\bar n + 1)`.  This is only a starting point for
    :func:`convergence.converge`, never a substitute for it: the
    package default ``N_basis=20`` is adequate for displacement and rotation but
    badly inadequate once radiation pressure is switched on.
    """
    return int(np.ceil(safety * (1.0 + float(kappa) ** 2) * (float(nbar) + 1.0)))


@lru_cache(maxsize=32)
def _x_eig(N_basis):
    """Eigendecomposition of x, cached: every unitary generated by a function of
    x alone is diagonal here, which covers the shear and the epsilon_a signal."""
    vals, vecs = np.linalg.eigh(x_quadrature(N_basis).full())
    return vals, vecs


@lru_cache(maxsize=32)
def _p_eig(N_basis):
    vals, vecs = np.linalg.eigh(p_quadrature(N_basis).full())
    return vals, vecs


@lru_cache(maxsize=64)
def _loss_weights(N_basis, eta):
    r"""Coefficients :math:`c_k(m) = \eta^{m/2}\sqrt{(1-\eta)^k \binom{m+k}{k}}`.

    These are the Kraus operators :math:`K_k = \sqrt{(1-\eta)^k/k!}\,\eta^{\hat n/2} a^k`
    written in the Fock basis, so that
    :math:`\Lambda(\rho)_{mn} = \sum_k c_k(m) c_k(n) \rho_{m+k,n+k}`.
    """
    k = np.arange(N_basis)[:, None]
    m = np.arange(N_basis)[None, :]
    log_binom = gammaln(m + k + 1.0) - gammaln(k + 1.0) - gammaln(m + 1.0)
    return np.exp(0.5 * (m * np.log(eta) + k * np.log1p(-eta) + log_binom))


def _support(*mats, rtol=1e-15):
    """Highest Fock index carrying non-negligible weight in any of ``mats``."""
    idx = 0
    for mat in mats:
        rows = np.abs(mat).max(axis=1)
        scale = rows.max()
        if scale <= 0:
            continue
        nz = np.nonzero(rows > rtol * scale)[0]
        if nz.size:
            idx = max(idx, int(nz[-1]))
    return idx


def _kraus_order(rho, tol=1e-14):
    """Highest Kraus order that can contribute to the loss sum.

    ``K_k`` annihilates ``k`` photons, so orders above the occupied photon number
    contribute nothing.  Bounding by the cumulative population from the top is
    far tighter than bounding by numerical support: the *truncated* shear leaves
    round-off-level amplitude across the whole space, which would otherwise force
    the sum to run to the cutoff.
    """
    diag = np.abs(np.real(np.diag(rho)))
    total = diag.sum()
    if total <= 0:
        return 0
    tail = np.cumsum(diag[::-1])[::-1]
    keep = np.nonzero(tail > tol * total)[0]
    return int(keep[-1]) if keep.size else 0


def _loss_exact(rho, eta):
    """Bosonic loss of transmissivity ``eta``, applied as a shifted-diagonal sum.

    Equivalent to damping with ``loss_to_kappa(1 - eta)`` over unit time, which is
    what :mod:`dynamics` does, but O(support * N^2) instead of an
    N^2-dimensional ODE.
    """
    eta = float(eta)
    if eta >= 1.0:
        return rho
    N = rho.shape[0]
    if eta <= 0.0:
        out = np.zeros_like(rho)
        out[0, 0] = np.trace(rho)
        return out
    w = _loss_weights(N, eta)
    out = np.zeros_like(rho, dtype=complex)
    for k in range(_kraus_order(rho) + 1):
        size = N - k
        wk = w[k, :size]
        out[:size, :size] += rho[k:, k:] * (wk[:, None] * wk[None, :])
    return out


def _dephasing_exact(rho, pn):
    r"""Gaussian phase noise: :math:`\rho_{mn} \to \rho_{mn} e^{-\sigma^2 (m-n)^2/2}`.

    Equivalent to a Lindblad :math:`\sqrt{\chi}\,\hat n` with
    ``chi = phirms_to_chi(pn)`` over unit time.
    """
    pn = float(pn)
    if pn <= 0.0:
        return rho
    idx = np.arange(rho.shape[0])
    return rho * np.exp(-0.5 * pn**2 * (idx[:, None] - idx[None, :]) ** 2)


def _quadratic_unitary(N_basis, kappa, c_x, c_p, Delta, t):
    r"""``exp(-i t H)`` for ``H = Delta n + c_x x + c_p p + kappa x^2 / (2 t)``.

    Uses the cached quadrature eigenbasis whenever the generator is a function of
    a single quadrature (the case for every study here), and falls back to a
    dense matrix exponential otherwise.
    """
    if Delta == 0.0 and c_p == 0.0:
        vals, vecs = _x_eig(N_basis)
        phase = np.exp(-1j * (t * c_x * vals + 0.5 * kappa * vals**2))
        return (vecs * phase) @ vecs.conj().T
    if Delta == 0.0 and c_x == 0.0 and kappa == 0.0:
        vals, vecs = _p_eig(N_basis)
        return (vecs * np.exp(-1j * t * c_p * vals)) @ vecs.conj().T
    x = x_quadrature(N_basis).full()
    H = Delta * np.diag(np.arange(N_basis, dtype=float)) + c_x * x
    if c_p:
        H = H + c_p * p_quadrature(N_basis).full()
    if kappa:
        H = H + (kappa / (2.0 * t)) * (x @ x)
    return expm(-1j * t * H)


def _concurrent_exact(rho, N_basis, kappa, c_x, c_p, Delta, t_final,
                      eta_ch, pn_ch, n_steps):
    r"""Back-action, signal and dissipation acting *together*, by Strang splitting.

    The three concurrent pieces each have an exact closed form, and both
    dissipators compose exactly under time splitting -- loss of transmissivity
    :math:`\eta` is :math:`n` steps of :math:`\eta^{1/n}`, and dephasing of
    strength :math:`\sigma` is :math:`n` steps of :math:`\sigma/\sqrt n`.  So the
    only error is the Trotter split between the Hamiltonian and the dissipator,
    which Strang ordering makes :math:`O((t/n)^2)`.

    This exists because the alternative -- handing the whole thing to
    ``mesolve`` -- propagates an :math:`N^2`-dimensional Liouvillian and cannot
    reach the cutoffs the shear demands: 4.5 s at ``N_basis=160`` against 1.6 s
    at ``N_basis=150`` here, and the gap widens fast with the cutoff.  Accuracy
    is checked against ``mesolve`` in ``test_concurrent_exact_matches_mesolve``
    (agreement 1e-6 or better); the speed claim is a benchmark, not a test,
    because wall-clock assertions fail spuriously under load.
    """
    eta_half = eta_ch ** (0.5 / n_steps)
    pn_half = pn_ch / np.sqrt(2.0 * n_steps)
    eta_full = eta_ch ** (1.0 / n_steps)
    pn_full = pn_ch / np.sqrt(n_steps)
    U = _quadratic_unitary(N_basis, kappa / n_steps, c_x, c_p, Delta, t_final / n_steps)
    Ud = U.conj().T

    def dissipate(arr, eta, pn):
        return _loss_exact(_dephasing_exact(arr, pn), eta)

    arr = dissipate(rho, eta_half, pn_half)
    for k in range(n_steps):
        arr = U @ arr @ Ud
        arr = dissipate(arr, eta_half, pn_half) if k == n_steps - 1 else dissipate(arr, eta_full, pn_full)
    return arr


def _project_to_state(arr):
    """Nearest valid density matrix: Hermitian, positive, unit trace.

    Richardson extrapolation is a signed combination of two density matrices, so
    it can leave eigenvalues a few 1e-9 below zero.  The QFI sums
    ``|drho_ij|^2 / (p_i + p_j)``, where a small *negative* denominator is far
    worse than a small positive one, so the extrapolated matrix is projected
    back before use.
    """
    arr = 0.5 * (arr + arr.conj().T)
    w, v = np.linalg.eigh(arr)
    if w.min() >= 0.0:
        return arr
    w = np.clip(w, 0.0, None)
    out = (v * w) @ v.conj().T
    return out / np.trace(out).real


def _auto_trotter_steps(kappa, c_x, c_p, Delta, t_final, eta_ch, pn_ch):
    """Step count for the Strang split, from how fast each concurrent piece acts.

    Scaled off the largest generator strength over the interaction; the floor of
    64 keeps short/weak channels comfortably converged, and the result is
    validated against ``mesolve`` rather than assumed.
    """
    strength = abs(kappa) + t_final * (abs(c_x) + abs(c_p) + abs(Delta))
    strength += abs(np.log(max(eta_ch, 1e-12))) + pn_ch**2
    return int(max(24, np.ceil(10 * strength)))


def _ensure_dm(state):
    return qt.ket2dm(state) if state.isket else state


def _noise_stage(rho, eta, pn, t_stage=1.0, solver="exact"):
    """Loss + dephasing as a single mesolve stage, matching the package convention.

    ``loss_to_kappa(1 - eta)`` damped over unit time gives transmissivity ``eta``;
    ``phirms_to_chi(pn)`` on the number operator gives
    ``rho_mn -> rho_mn exp(-pn^2 (m-n)^2 / 2)``.  The two commute, so applying
    them together or in sequence is equivalent.
    """
    if eta >= 1.0 and pn <= 0.0:
        return rho
    if solver == "exact":
        arr = _dephasing_exact(rho.full(), pn)
        return qt.Qobj(_loss_exact(arr, eta))

    N_basis = rho.shape[0]
    a = qt.destroy(N_basis)
    n_op = a.dag() * a

    c_ops = []
    if eta < 1.0:
        c_ops.append(np.sqrt(loss_to_kappa(1 - eta, t_stage)) * a)
    if pn > 0.0:
        c_ops.append(np.sqrt(phirms_to_chi(pn, t_stage)) * n_op)
    if not c_ops:
        return rho

    res = qt.mesolve(0 * n_op, rho, [0.0, t_stage], c_ops, options=_SOLVER_OPTIONS)
    return res.states[-1]


def get_state_single_mode_ba(
    *,
    kappa=0.0,
    ordering="BA3",
    Delta=0.0,
    epsilon_a=0.0,
    epsilon_p=0.0,
    eta_in=1.0,
    eta_ch=1.0,
    eta_out=1.0,
    pn_in=0.0,
    pn_ch=0.0,
    pn_out=0.0,
    sigma_a=0.0,
    sigma_p=0.0,
    t_final=1.0,
    N_basis=20,
    rho=None,
    solver="exact",
    n_trotter=None,
):
    """
    Single-mode sensing channel *with* radiation-pressure back-action.

    Same signature and staging as
    :func:`dynamics.get_state_single_mode`, plus ``kappa`` and
    ``ordering``.  With ``kappa = 0`` (or ``ordering="none"``) it reduces to that
    function exactly.

    Pipeline::

        input -> [eta_in, pn_in] -> [ back-action / sensing, per `ordering` ]
              -> [eta_out, pn_out] -> output

    Parameters
    ----------
    kappa : float
        Opto-mechanical coupling at this sideband frequency.  For a free-mass
        interferometer :math:`\\kappa(\\Omega) = 2(I_0/I_{\\rm SQL})\\gamma^4 /
        [\\Omega^2(\\gamma^2+\\Omega^2)]`.
    ordering : {"none", "BA1", "BA2", "BA3"}
        Where radiation pressure sits relative to the signal.  ``"BA3"`` is the
        physical case and is the default.
    Delta, epsilon_a, epsilon_p, eta_*, pn_*, sigma_*, t_final, N_basis, rho
        As in :func:`dynamics.get_state_single_mode`.
        ``epsilon_a`` is the gravitational-wave signal quadrature.
    solver : {"exact", "mesolve"}
        ``"exact"`` (default) applies closed-form maps; ``"mesolve"`` reproduces
        the integrator used by :mod:`dynamics`.  The two agree to
        solver tolerance, but only ``"exact"`` is usable at the cutoffs radiation
        pressure requires.  Concurrent loss and dephasing (``eta_ch``, ``pn_ch``)
        are handled exactly by Strang splitting; ``sigma_a``/``sigma_p`` have no
        closed-form map and always fall back to the integrator.
    n_trotter : int, optional
        Strang steps for the concurrent path.  ``None`` picks a count from the
        generator strengths.

    Returns
    -------
    qutip.Qobj
        Output density matrix.
    """
    if ordering not in ORDERINGS:
        raise ValueError(f"ordering must be one of {ORDERINGS}, got {ordering!r}")
    if solver not in SOLVERS:
        raise ValueError(f"solver must be one of {SOLVERS}, got {solver!r}")

    if rho is None:
        rho0 = qt.ket2dm(qt.coherent(N_basis, 1.0))
    else:
        rho0 = _ensure_dm(rho)
    N_basis = rho0.shape[0]

    a = qt.destroy(N_basis)
    n_op = a.dag() * a

    # --- Stage 1: input noise (injection loss, input phase noise) -----------
    rho1 = _noise_stage(rho0, eta_in, pn_in, solver=solver)

    # --- Stage 2: back-action and sensing ----------------------------------
    H_sense = Delta * n_op + epsilon_a * (a.dag() + a) + 1j * epsilon_p * (a.dag() - a)

    L_ch = []
    if eta_ch < 1.0:
        L_ch.append(np.sqrt(loss_to_kappa(1 - eta_ch, t_final)) * a)
    if pn_ch > 0.0:
        L_ch.append(np.sqrt(phirms_to_chi(pn_ch, t_final)) * n_op)
    if sigma_a > 0.0:
        L_ch.append(np.sqrt(sigma_a) * (a.dag() + a))
    if sigma_p > 0.0:
        L_ch.append(1j * np.sqrt(sigma_p) * (a.dag() - a))

    def _sense(state):
        res = qt.mesolve(H_sense, state, [0.0, t_final], L_ch, options=_SOLVER_OPTIONS)
        return res.states[-1]

    c_x, c_p = np.sqrt(2.0) * epsilon_a, np.sqrt(2.0) * epsilon_p
    # sigma_a / sigma_p have no closed-form map here, so they force the integrator;
    # concurrent loss and dephasing are handled exactly by Strang splitting.
    concurrent = (eta_ch < 1.0) or (pn_ch > 0.0)
    exotic = (sigma_a > 0.0) or (sigma_p > 0.0)
    use_exact = solver == "exact" and not exotic

    if use_exact and concurrent:
        n = n_trotter or _auto_trotter_steps(kappa if ordering == "BA3" else 0.0,
                                             c_x, c_p, Delta, t_final, eta_ch, pn_ch)
        arr = rho1.full()
        if ordering == "BA1":  # the whole shear lands before the interaction
            U0 = _backaction_unitary_cached(N_basis, float(kappa))
            arr = U0 @ arr @ U0.conj().T
        ba_now = kappa if ordering == "BA3" else 0.0
        # The Strang error is cleanly O(1/n^2) (verified: the error falls by a
        # factor 4.00 per doubling), so one Richardson step on the density
        # matrix buys O(1/n^4) for 1.5x the work of the 2n run alone.
        low = _concurrent_exact(arr, N_basis, ba_now, c_x, c_p, Delta, t_final,
                                eta_ch, pn_ch, n)
        high = _concurrent_exact(arr, N_basis, ba_now, c_x, c_p, Delta, t_final,
                                 eta_ch, pn_ch, 2 * n)
        arr = (4.0 * high - low) / 3.0
        arr = _project_to_state(arr)
        if ordering == "BA2":  # ...or after it
            U0 = _backaction_unitary_cached(N_basis, float(kappa))
            arr = U0 @ arr @ U0.conj().T
        rho2 = qt.Qobj(arr)
    elif use_exact:
        ba = kappa if ordering == "BA3" else 0.0
        U_sense = _quadratic_unitary(N_basis, ba, c_x, c_p, Delta, t_final)
        if ordering == "none" or kappa == 0.0 or ordering == "BA3":
            U = U_sense
        elif ordering == "BA1":  # radiation pressure -> displacement sensing
            U = U_sense @ _backaction_unitary_cached(N_basis, float(kappa))
        else:  # BA2: displacement sensing -> radiation pressure
            U = _backaction_unitary_cached(N_basis, float(kappa)) @ U_sense
        arr = rho1.full()
        rho2 = qt.Qobj(U @ arr @ U.conj().T)
    elif ordering == "none" or kappa == 0.0:
        rho2 = _sense(rho1)
    elif ordering == "BA1":  # radiation pressure -> displacement sensing
        U = backaction_unitary(N_basis, kappa)
        rho2 = _sense(U * rho1 * U.dag())
    elif ordering == "BA2":  # displacement sensing -> radiation pressure
        U = backaction_unitary(N_basis, kappa)
        rho2 = U * _sense(rho1) * U.dag()
    else:  # BA3, simultaneous
        H = H_sense + backaction_hamiltonian(N_basis, kappa, t_final)
        rho2 = qt.mesolve(H, rho1, [0.0, t_final], L_ch, options=_SOLVER_OPTIONS).states[-1]

    # --- Stage 3: output noise (detection loss, output phase noise) --------
    return _noise_stage(rho2, eta_out, pn_out, solver=solver)
