"""
Radiation-pressure backaction channels for single-mode QFI studies.

Implements the per-frequency, light-only description of backaction: the mirror
is eliminated and radiation pressure acts on the optical mode as a unitary,
composable with the repo's loss/dephasing stages. Two backaction forms:

  - "shear": linearized ponderomotive unitary U = exp(-i (chi/2) X_theta^2).
    For theta_ba = 0 this maps x -> x, p -> p - chi*x (amplitude fluctuations
    written onto the phase quadrature). Equivalent to rotation-squeeze-rotation
    with squeeze parameter r = arcsinh(chi/2).
  - "kerr": full self-phase-modulation U = exp(-i chi n^2), the nonlinear
    ponderomotive form (adiabatically eliminated mirror, no linearization).

The signal is a quadrature displacement generated by X_theta_sig:
U_sig = exp(-i s X_theta_sig), which translates the orthogonal quadrature
X_{theta_sig + pi/2} by -s (the sign is irrelevant for Fisher information;
the metrology convention rho_s = e^{-i s G} rho e^{+i s G} with G = X_theta_sig
gives lossless pure-state QFI = 4 Var(G)). With the defaults (theta_sig = theta_ba = 0) the
signal displaces the phase quadrature and backaction is driven by the
amplitude quadrature — the GW-like configuration, where signal generator X_0
commutes with the shear generator X_0^2 (so lossless QFI is shear-independent)
but NOT with the Kerr generator n^2.

Quadrature convention: X_theta = (a e^{-i theta} + a† e^{i theta})/sqrt(2),
so X_0 = x, X_{pi/2} = p, [x, p] = i, vacuum variance 1/2. Lossless pure-state
QFI for the displacement signal is 4 Var(X_theta_sig) of the state entering
the signal stage.

Channel chains are ordered stage tuples, e.g.:
    ("ba", "sig")                       BA1: backaction then signal
    ("sig", "ba")                       BA2: signal then backaction
    ("basig",)                          BA3: simultaneous (one unitary)
    ("loss_in", "ba", "sig")            injection loss
    ("ba", "sig", "loss_out")           detection loss
    ("pn", "ba", "sig", "loss_out")     phase noise -> BA -> loss

Mean photon number constraints refer to the INPUT state (the optical resource
budget); the shear adds photons downstream by construction.
"""

import numpy as np
import qutip as qt
from scipy.optimize import brentq

from .conversions import phirms_to_chi
from .sld import calculate_qfi

STATE_FAMILIES = ("coherent", "squeezed", "fock", "cat", "sqz_cat")

VALID_STAGES = ("sig", "ba", "basig", "loss_in", "loss_out", "pn")


# ---------------------------------------------------------------------------
# Operators and unitaries
# ---------------------------------------------------------------------------

def quadrature(N_basis, theta=0.0):
    """X_theta = (a e^{-i theta} + a† e^{i theta}) / sqrt(2)."""
    a = qt.destroy(N_basis)
    return (a * np.exp(-1j * theta) + a.dag() * np.exp(1j * theta)) / np.sqrt(2)


def signal_generator(N_basis, theta_sig=0.0):
    """Generator of the displacement signal: X_theta_sig.

    U_sig = exp(-i s X_theta_sig) translates X_{theta_sig + pi/2} by -s.
    """
    return quadrature(N_basis, theta_sig)


def ba_generator(chi, N_basis, ba_type="shear", theta_ba=0.0):
    """
    Backaction generator G such that U_ba = exp(-i G).

    shear: G = (chi/2) X_theta_ba^2   (linearized ponderomotive)
    kerr:  G = chi n^2                (self-phase modulation)
    """
    if ba_type == "shear":
        X = quadrature(N_basis, theta_ba)
        return 0.5 * chi * X * X
    elif ba_type == "kerr":
        n_op = qt.num(N_basis)
        return chi * n_op * n_op
    raise ValueError(f"ba_type must be 'shear' or 'kerr', got {ba_type!r}")


def shear_squeeze_r(chi):
    """Squeeze parameter of the ponderomotive shear: r = arcsinh(chi/2)."""
    return np.arcsinh(chi / 2.0)


def quadrature_covariance(state):
    """
    Symmetrized 2x2 covariance matrix of (x, p) for a ket or density matrix:
    C_ij = <{A_i, A_j}>/2 - <A_i><A_j>.
    """
    N_basis = state.shape[0]
    x = quadrature(N_basis, 0.0)
    p = quadrature(N_basis, np.pi / 2)
    ops = [x, p]
    C = np.zeros((2, 2))
    for i, A in enumerate(ops):
        for j, B in enumerate(ops):
            C[i, j] = (0.5 * qt.expect(A * B + B * A, state).real
                       - qt.expect(A, state).real * qt.expect(B, state).real)
    return C


def _apply_unitary(state, U):
    if state.isket:
        return U * state
    return U * state * U.dag()


def _loss_channel(state, eta, N_basis):
    """
    Exact bosonic attenuation channel of transmission eta (identical to the
    unit-time Lindblad sqrt(kappa)*a evolution with e^{-kappa} = eta, applied
    in closed Kraus form: K_k = sqrt((1-eta)^k / k!) eta^{n/2} a^k).
    """
    if eta >= 1.0:
        return state
    rho = qt.ket2dm(state) if state.isket else state
    R = rho.full()
    d_half = eta ** (np.arange(N_basis) / 2.0)
    s = np.sqrt(np.arange(1, N_basis))  # a M a† is an index shift, O(N^2)
    out = np.zeros_like(R)
    # Fold (1-eta)^k / k! into the iterate as it is built, so M holds the
    # bounded, Poisson-weighted K_k rho K_k† core (a bare a^k rho a†^k
    # overflows float64 once k gets large).
    M = R.copy()
    target = np.trace(R).real
    acc = 0.0
    for k in range(N_basis):
        if k > 0:
            M_next = np.zeros_like(M)
            M_next[:-1, :-1] = (M[1:, 1:] * s[:, None] * s[None, :]
                                * ((1.0 - eta) / k))
            M = M_next
        term = (d_half[:, None] * M) * d_half[None, :]
        out += term
        acc += np.trace(term).real
        if target - acc < 1e-14:
            break
    return qt.Qobj(out, dims=rho.dims)


def _dephasing_channel(state, pn, N_basis):
    """
    Exact number dephasing: rho_nm -> rho_nm exp(-chi (n-m)^2 / 2) with
    chi = phirms_to_chi(pn) (identical to unit-time Lindblad sqrt(chi)*n).
    """
    if pn <= 0.0:
        return state
    rho = qt.ket2dm(state) if state.isket else state
    chi = phirms_to_chi(pn)
    n = np.arange(N_basis)
    mask = np.exp(-0.5 * chi * (n[:, None] - n[None, :]) ** 2)
    return qt.Qobj(rho.full() * mask, dims=rho.dims)


# ---------------------------------------------------------------------------
# Fixed-<n> state factory
# ---------------------------------------------------------------------------

def _cat_ket(alpha, N_basis, parity=+1):
    psi = qt.coherent(N_basis, alpha) + parity * qt.coherent(N_basis, -alpha)
    return psi.unit()


def _solve_alpha_for_nbar(build, nbar, alpha_hi):
    """Find alpha >= 0 with <n>(build(alpha)) = nbar by bisection."""
    def f(alpha):
        psi = build(alpha)
        return qt.expect(qt.num(psi.shape[0]), psi) - nbar

    lo, hi = 0.0, alpha_hi
    if f(lo) > 1e-12:
        raise ValueError(f"Target nbar={nbar} below the family's minimum <n>={f(lo)+nbar:.4f}.")
    if abs(f(lo)) <= 1e-12:
        return lo
    while f(hi) < 0:
        hi *= 1.5
        if hi > 1e3:
            raise ValueError("Could not bracket alpha for target nbar; raise N_basis?")
    return brentq(f, lo, hi, xtol=1e-12)


def make_state(family, nbar, N_basis, squeeze_angle=0.0, sqz_fraction=0.5,
               parity=+1):
    """
    Build a normalized ket with mean photon number nbar.

    Families
    --------
    coherent : |alpha>, alpha = sqrt(nbar)
    squeezed : S(r e^{i squeeze_angle})|0>, sinh^2 r = nbar
    fock     : |round(nbar)>  (nbar must be near-integer)
    cat      : N(|alpha> + parity|-alpha>), alpha solved numerically
    sqz_cat  : S(r) N(|alpha> + parity|-alpha>); sinh^2 r = sqz_fraction*nbar,
               alpha solved numerically for total <n> = nbar

    Angles follow QuTiP's squeeze convention: real positive argument squeezes
    the x quadrature (Var x = e^{-2r}/2) and anti-squeezes p.
    """
    if nbar < 0:
        raise ValueError("nbar must be non-negative")

    if family == "coherent":
        return qt.coherent(N_basis, np.sqrt(nbar))

    if family == "squeezed":
        r = np.arcsinh(np.sqrt(nbar))
        if r == 0.0:
            return qt.basis(N_basis, 0)
        return (qt.squeeze(N_basis, r * np.exp(1j * squeeze_angle))
                * qt.basis(N_basis, 0)).unit()

    if family == "fock":
        n = int(round(nbar))
        if abs(n - nbar) > 1e-9:
            raise ValueError(f"fock family needs integer nbar, got {nbar}")
        if n >= N_basis:
            raise ValueError(f"fock n={n} needs N_basis > {n}")
        return qt.basis(N_basis, n)

    if family == "cat":
        alpha = _solve_alpha_for_nbar(
            lambda al: _cat_ket(al, N_basis, parity), nbar,
            alpha_hi=np.sqrt(nbar) + 2.0)
        return _cat_ket(alpha, N_basis, parity)

    if family == "sqz_cat":
        r = np.arcsinh(np.sqrt(sqz_fraction * nbar))
        S = qt.squeeze(N_basis, r * np.exp(1j * squeeze_angle))
        build = lambda al: (S * _cat_ket(al, N_basis, parity)).unit()
        alpha = _solve_alpha_for_nbar(build, nbar,
                                      alpha_hi=np.sqrt(nbar) + 2.0)
        return build(alpha)

    raise ValueError(f"Unknown family {family!r}; choose from {STATE_FAMILIES}")


def mean_photon_number(state):
    """<n> of a ket or density matrix."""
    N_basis = state.shape[0]
    return float(qt.expect(qt.num(N_basis), state))


# ---------------------------------------------------------------------------
# Backaction channel
# ---------------------------------------------------------------------------

def get_state_backaction(
    *,
    s=0.0,
    chi_ba=0.0,
    ba_type="shear",
    theta_sig=0.0,
    theta_ba=0.0,
    chain=("ba", "sig"),
    eta_in=1.0,
    eta_out=1.0,
    pn=0.0,
    state="coherent",
    nbar=4.0,
    squeeze_angle=0.0,
    sqz_fraction=0.5,
    parity=+1,
    N_basis=40,
    rho=None,
):
    """
    Apply an ordered chain of signal / backaction / noise stages to an input
    state and return the output (ket for unitary-only chains, else dm).

    Parameters
    ----------
    s        : displacement signal amplitude (the estimated parameter;
               use param_type="s" with calculate_qfi / calculate_sld)
    chi_ba   : backaction strength (shear chi or Kerr phase per photon^2)
    ba_type  : "shear" (linearized ponderomotive) or "kerr" (n^2)
    chain    : ordered stage names from
               ("sig", "ba", "basig", "loss_in", "loss_out", "pn");
               "basig" applies exp(-i (s X_sig + G_ba)) in one unitary (BA3)
    eta_in, eta_out : transmissions of the loss_in / loss_out stages
    pn       : phase-noise rms (rad) of the pn stage
    state, nbar, squeeze_angle, sqz_fraction, parity :
               input-state family and options (see make_state); ignored when
               rho is given
    rho      : optional explicit input ket/dm (dimension must equal N_basis)
    """
    for st in chain:
        if st not in VALID_STAGES:
            raise ValueError(f"Unknown stage {st!r}; valid: {VALID_STAGES}")

    if rho is not None:
        if rho.shape[0] != N_basis:
            raise ValueError(
                f"rho dimension {rho.shape[0]} != N_basis {N_basis}")
        out = rho
    else:
        out = make_state(state, nbar, N_basis, squeeze_angle=squeeze_angle,
                         sqz_fraction=sqz_fraction, parity=parity)

    for st in chain:
        if st == "sig":
            U = (-1j * s * signal_generator(N_basis, theta_sig)).expm()
            out = _apply_unitary(out, U)
        elif st == "ba":
            if chi_ba != 0.0:
                U = (-1j * ba_generator(chi_ba, N_basis, ba_type, theta_ba)).expm()
                out = _apply_unitary(out, U)
        elif st == "basig":
            G = s * signal_generator(N_basis, theta_sig)
            if chi_ba != 0.0:
                G = G + ba_generator(chi_ba, N_basis, ba_type, theta_ba)
            out = _apply_unitary(out, (-1j * G).expm())
        elif st == "loss_in":
            out = _loss_channel(out, eta_in, N_basis)
        elif st == "loss_out":
            out = _loss_channel(out, eta_out, N_basis)
        elif st == "pn":
            out = _dephasing_channel(out, pn, N_basis)

    return out


# ---------------------------------------------------------------------------
# Fock-cutoff convergence
# ---------------------------------------------------------------------------

def calculate_qfi_converged(dynamics=get_state_backaction, *, param_value=0.0,
                            param_type="s", N_start=30, N_max=400,
                            growth=1.5, rtol=1e-4, **kwargs):
    """
    Compute QFI with an automated Fock-cutoff convergence check: grow N_basis
    geometrically until successive QFI values agree to rtol.

    Returns (qfi, N_used, history) with history = [(N_basis, qfi), ...].
    The dynamics callable must accept N_basis and build its input state at
    that dimension (do not pass a fixed rho).
    """
    history = []
    N = int(N_start)
    q_prev = calculate_qfi(dynamics, param_value=param_value,
                           param_type=param_type, N_basis=N, **kwargs)
    history.append((N, q_prev))
    while True:
        N_next = max(N + 5, int(np.ceil(N * growth)))
        if N_next > N_max:
            raise RuntimeError(
                f"QFI not converged to rtol={rtol} by N_basis={N}: "
                f"history={history}")
        q_next = calculate_qfi(dynamics, param_value=param_value,
                               param_type=param_type, N_basis=N_next, **kwargs)
        history.append((N_next, q_next))
        scale = max(abs(q_next), 1e-30)
        if abs(q_next - q_prev) / scale < rtol:
            return q_next, N_next, history
        N, q_prev = N_next, q_next
