r"""Conventions used throughout the package.

Units and quadratures
---------------------
We work with :math:`\hbar = 1` and the dimensionless quadratures

.. math::
    \hat{x} = \frac{a + a^\dagger}{\sqrt{2}}, \qquad
    \hat{p} = \frac{a - a^\dagger}{i\sqrt{2}}, \qquad [\hat x, \hat p] = i,

so that the vacuum has :math:`\mathrm{Var}(x) = \mathrm{Var}(p) = 1/2` and the
covariance matrix of the vacuum is :math:`V_{\rm vac} = \tfrac12 \mathbb{1}`.

Relation to the two-photon (Caves--Schumaker / Kimble) quadratures
------------------------------------------------------------------
Kimble et al. (Phys. Rev. D 65, 022002) normalise the sideband quadratures
:math:`a_1, a_2` so that the vacuum single-sided spectral density is unity.
The dictionary is

.. math::   a_1 = \sqrt{2}\,\hat x, \qquad a_2 = \sqrt{2}\,\hat p .

Their lossless input--output relation for a free-mass interferometer
(with the overall :math:`e^{2i\beta}` propagation phase dropped, since a
rotation neither changes the QFI nor the physics of interest here) is

.. math::
    b_1 = a_1, \qquad b_2 = a_2 - \kappa\, a_1 + \sqrt{2\kappa}\, h/h_{\rm SQL}.

In our quadratures this reads

.. math::
    x \to x, \qquad p \to p - \kappa x + \lambda, \qquad
    \lambda \equiv \sqrt{\kappa}\, h / h_{\rm SQL}.

Radiation pressure ("back-action") is therefore the **shear**
:math:`S(\kappa) = \begin{pmatrix} 1 & 0\\ -\kappa & 1\end{pmatrix}`, which is
generated by the unitary

.. math::   U_{\rm BA}(\kappa) = \exp\!\left(-\tfrac{i}{2}\,\kappa\, \hat x^2\right),

and the gravitational-wave signal is a **displacement along p** generated by
:math:`\hat x`,

.. math::   U_{\rm sig}(\lambda) = \exp\!\left(+ i\,\lambda\, \hat x\right).

Signal quadrature angle
-----------------------
For generality every routine accepts a signal-quadrature angle
:math:`\varphi`, with generator
:math:`\hat q_\varphi = \cos\varphi\,\hat x + \sin\varphi\,\hat p`.
:math:`\varphi = 0` (the default) is the physical free-mass case above, in
which the signal generator commutes with the back-action generator.
"""

import numpy as np

VACUUM_VARIANCE = 0.5
V_VAC = 0.5 * np.eye(2)

__all__ = ["VACUUM_VARIANCE", "V_VAC"]
