r"""Gaussian (covariance-matrix) track.

Everything here is exact for Gaussian states and Gaussian channels and is used
both as a fast production tool and as a set of analytic unit tests for the
Fock-space code.

Ordering of the phase-space vector is :math:`(x, p)` with
:math:`V_{\rm vac} = \tfrac12\mathbb{1}` (see :mod:`ligo_backaction.conventions`).
"""

from __future__ import annotations

from dataclasses import dataclass, replace

import numpy as np

from .conventions import V_VAC

__all__ = [
    "GaussianState",
    "vacuum",
    "squeezed_vacuum_gaussian",
    "squeezed_vacuum_at_fixed_nbar",
    "optimal_squeeze_angle",
    "coherent_gaussian",
    "shear_matrix",
    "squeeze_matrix",
    "rotation_matrix",
    "shear_to_squeeze_rotation",
    "apply_symplectic",
    "apply_loss",
    "apply_displacement",
    "gaussian_qfi_mean",
    "run_gaussian_channel",
    "gaussian_qfi_lambda",
    "fd_squeeze_angle",
    "homodyne_noise_spectrum",
]


@dataclass
class GaussianState:
    """First and second moments of a single-mode Gaussian state."""

    mean: np.ndarray  # shape (2,)
    cov: np.ndarray  # shape (2, 2)
    dmean: np.ndarray | None = None  # d(mean)/d(parameter), shape (2,)

    def __post_init__(self):
        self.mean = np.asarray(self.mean, dtype=float).reshape(2)
        self.cov = np.asarray(self.cov, dtype=float).reshape(2, 2)
        if self.dmean is None:
            self.dmean = np.zeros(2)
        else:
            self.dmean = np.asarray(self.dmean, dtype=float).reshape(2)

    def copy(self) -> "GaussianState":
        return replace(self, mean=self.mean.copy(), cov=self.cov.copy(), dmean=self.dmean.copy())

    @property
    def nbar(self) -> float:
        """Mean photon number :math:`\\tfrac12(\\mathrm{tr}V - 1) + \\tfrac12|d|^2`."""
        return 0.5 * (np.trace(self.cov) - 1.0) + 0.5 * float(self.mean @ self.mean)


def vacuum() -> GaussianState:
    return GaussianState(np.zeros(2), V_VAC.copy())


def squeezed_vacuum_gaussian(r: float, theta: float = 0.0) -> GaussianState:
    r"""Squeezed vacuum with :math:`\mathrm{Var}(x) = e^{2r}/2` for ``theta = 0``.

    ``r > 0`` therefore *anti*-squeezes :math:`x` (the quadrature conjugate to
    the signal displacement), which is the configuration that increases the QFI.
    """
    v = 0.5 * np.diag([np.exp(2 * r), np.exp(-2 * r)])
    rot = rotation_matrix(theta)
    return GaussianState(np.zeros(2), rot @ v @ rot.T)


def coherent_gaussian(alpha: complex) -> GaussianState:
    mean = np.array([np.sqrt(2) * np.real(alpha), np.sqrt(2) * np.imag(alpha)])
    return GaussianState(mean, V_VAC.copy())


def shear_matrix(kappa: float) -> np.ndarray:
    r"""Ponderomotive shear :math:`S = \begin{pmatrix}1&0\\-\kappa&1\end{pmatrix}`."""
    return np.array([[1.0, 0.0], [-float(kappa), 1.0]])


def squeeze_matrix(r: float) -> np.ndarray:
    return np.diag([np.exp(r), np.exp(-r)])


def rotation_matrix(theta: float) -> np.ndarray:
    c, s = np.cos(theta), np.sin(theta)
    return np.array([[c, -s], [s, c]])


def shear_to_squeeze_rotation(kappa: float):
    r"""Decompose the ponderomotive shear into rotation - squeeze - rotation.

    Returns ``(r, theta_pre, theta_post)`` such that

    .. math:: S(\kappa) = R(\theta_{\rm post})\, \mathrm{diag}(e^{r}, e^{-r})\, R(\theta_{\rm pre}) .

    This is the "linearised ponderomotive form: squeezing plus rotation" of the
    single-mode optical response, with squeeze factor set by
    :math:`e^{r} - e^{-r} = \kappa` (i.e. :math:`r = \mathrm{arcsinh}(\kappa/2)`)
    and an accompanying frequency-dependent rotation.
    """
    kappa = float(kappa)
    s = shear_matrix(kappa)
    u, sv, vh = np.linalg.svd(s)
    # Force det = +1 on both orthogonal factors so they are genuine rotations.
    if np.linalg.det(u) < 0:
        u[:, 1] *= -1
        vh[1, :] *= -1
    r = float(np.log(sv[0]))
    theta_post = float(np.arctan2(u[1, 0], u[0, 0]))
    theta_pre = float(np.arctan2(vh[1, 0], vh[1, 1]))
    # vh is R(theta_pre); recover its angle robustly from the matrix itself.
    theta_pre = float(np.arctan2(vh[1, 0], vh[0, 0]))
    return r, theta_pre, theta_post


def apply_symplectic(state: GaussianState, S: np.ndarray) -> GaussianState:
    return GaussianState(S @ state.mean, S @ state.cov @ S.T, S @ state.dmean)


def apply_loss(state: GaussianState, eta: float) -> GaussianState:
    r"""Beamsplitter loss with power transmissivity ``eta`` (``eta = 1`` lossless)."""
    eta = float(eta)
    return GaussianState(
        np.sqrt(eta) * state.mean,
        eta * state.cov + (1.0 - eta) * V_VAC,
        np.sqrt(eta) * state.dmean,
    )


def apply_displacement(state: GaussianState, amount: float, phi: float = 0.0) -> GaussianState:
    r"""Displacement generated by :math:`\hat q_\varphi = \cos\varphi\,x + \sin\varphi\,p`.

    The generator :math:`\hat q_\varphi` displaces the *conjugate* direction:
    :math:`x \to x - \lambda\sin\varphi`, :math:`p \to p + \lambda\cos\varphi`.
    The derivative of the mean with respect to ``amount`` is accumulated in
    ``dmean`` so that the QFI can be read off downstream.
    """
    direction = np.array([-np.sin(phi), np.cos(phi)])
    out = state.copy()
    out.mean = state.mean + amount * direction
    out.dmean = state.dmean + direction
    return out


def gaussian_qfi_mean(state: GaussianState) -> float:
    r"""QFI for a parameter entering only through the first moments.

    .. math:: \mathcal{F} = (\partial_\theta d)^{\mathsf T} V^{-1} (\partial_\theta d).
    """
    return float(state.dmean @ np.linalg.solve(state.cov, state.dmean))


def fd_squeeze_angle(kappa):
    r"""Squeeze angle that realises frequency-dependent (filter-cavity) squeezing.

    The readout-quadrature noise vector is :math:`t = (\sin\zeta-\kappa\cos\zeta,\ \cos\zeta)`;
    aligning the squeezed axis of the input with ``t`` minimises the noise.  For
    the ordinary phase-quadrature readout (:math:`\zeta = 0`) this gives
    :math:`\theta(\Omega) = \arctan2(1, -\kappa) - \pi/2`.
    """
    kappa = np.asarray(kappa, dtype=float)
    return np.arctan2(1.0, -kappa) - 0.5 * np.pi


def homodyne_noise_spectrum(kappa, zeta=0.0, r=0.0, squeeze_angle=0.0, eta=1.0):
    r"""Strain noise of a homodyne readout, in units of :math:`h_{\rm SQL}^2`.

    Implements the standard free-mass input--output relation with squeezed
    input, readout quadrature ``zeta`` and detection efficiency ``eta``:

    .. math::
        b_\zeta = b_1\sin\zeta + b_2\cos\zeta,\quad
        b_1 = a_1,\quad b_2 = a_2 - \kappa a_1 + \sqrt{2\kappa}\,h/h_{\rm SQL}.

    * ``zeta = 0``, ``r = 0`` gives :math:`(1+\kappa^2)/(2\kappa)`, whose minimum
      over :math:`\kappa` is 1 -- the standard quantum limit.
    * :math:`\tan\zeta = \kappa` (variational readout) cancels the back-action
      term and gives :math:`1/(2\kappa)`, coinciding with the quantum
      Cramer--Rao bound for vacuum input.
    * ``squeeze_angle = fd_squeeze_angle(kappa)`` reproduces the filter-cavity
      result :math:`e^{-2r}(1+\kappa^2)/(2\kappa)`.

    All arguments broadcast against each other.

    Returns
    -------
    ndarray
        :math:`S_h/h_{\rm SQL}^2`.
    """
    kappa, zeta, r, theta, eta = np.broadcast_arrays(
        *(np.asarray(v, dtype=float) for v in (kappa, zeta, r, squeeze_angle, eta))
    )
    ep, em = np.exp(2 * r), np.exp(-2 * r)
    c, s = np.cos(theta), np.sin(theta)
    v11 = ep * c**2 + em * s**2
    v22 = ep * s**2 + em * c**2
    v12 = (ep - em) * s * c

    t1 = np.sin(zeta) - kappa * np.cos(zeta)
    t2 = np.cos(zeta)
    noise = eta * (t1**2 * v11 + 2 * t1 * t2 * v12 + t2**2 * v22) + (1.0 - eta) * (t1**2 + t2**2)
    signal = eta * 2.0 * kappa * np.cos(zeta) ** 2
    return noise / signal


def run_gaussian_channel(state: "GaussianState", spec) -> "GaussianState":
    r"""Gaussian mirror of :func:`ligo_backaction.channels.run_channel`.

    Accepts a :class:`~ligo_backaction.channels.ChannelSpec` and applies the same
    pipeline at the level of first and second moments, accumulating
    ``dmean = d(mean)/d(lambda)`` so that
    :func:`gaussian_qfi_mean` returns :math:`\mathcal{F}_\lambda`.

    Phase noise is *not* a Gaussian channel; ``sigma_in``/``sigma_out`` must be
    zero here (use the Fock track for phase noise).
    """
    if spec.sigma_in or spec.sigma_out:
        raise ValueError("phase noise is non-Gaussian; use the Fock track")
    s = state.copy()
    if spec.eta_in != 1.0:
        s = apply_loss(s, spec.eta_in)
    shear = shear_matrix(spec.kappa)
    if spec.ordering == "none":
        s = apply_displacement(s, spec.lam, spec.phi_sig)
    elif spec.ordering == "BA1":
        s = apply_displacement(apply_symplectic(s, shear), spec.lam, spec.phi_sig)
    elif spec.ordering == "BA2":
        s = apply_symplectic(apply_displacement(s, spec.lam, spec.phi_sig), shear)
    elif spec.ordering == "BA3":
        # Simultaneous evolution: exponentiate the sum of the two generators.
        # For a linear + quadratic Hamiltonian the affine map is
        #   z -> S z + int_0^1 e^{A(1-t)} b dt,  with S = e^{A} the shear.
        direction = np.array([-np.sin(spec.phi_sig), np.cos(spec.phi_sig)])
        A = np.array([[0.0, 0.0], [-spec.kappa, 0.0]])
        # int_0^1 e^{A(1-t)} dt = I + A/2 (A is nilpotent of order 2)
        Mint = np.eye(2) + 0.5 * A
        s = apply_symplectic(s, shear)
        s = GaussianState(
            s.mean + spec.lam * (Mint @ direction),
            s.cov,
            s.dmean + Mint @ direction,
        )
    else:  # pragma: no cover - guarded by ChannelSpec
        raise ValueError(spec.ordering)
    if spec.eta_out != 1.0:
        s = apply_loss(s, spec.eta_out)
    return s


def gaussian_qfi_lambda(state: "GaussianState", spec) -> float:
    r""":math:`\mathcal{F}_\lambda` for a Gaussian input through ``spec``."""
    return gaussian_qfi_mean(run_gaussian_channel(state, spec))


def squeezed_vacuum_at_fixed_nbar(nbar: float, theta: float = 0.0) -> "GaussianState":
    r"""Squeezed vacuum with :math:`\sinh^2 r = \bar n`, rotated by ``theta``.

    At fixed photon number this is the whole Gaussian family worth considering
    for displacement sensing: a coherent displacement does not change the
    covariance and therefore does not change the QFI, so every photon should go
    into squeezing.  ``theta`` is then the only free knob -- it trades the
    phase-space extent along :math:`x` (which the signal generator rewards)
    against the extent along :math:`p` (which the shear inflates and loss then
    punishes).
    """
    return squeezed_vacuum_gaussian(np.arcsinh(np.sqrt(max(nbar, 0.0))), theta)


def optimal_squeeze_angle(nbar: float, spec, n_grid: int = 721):
    r"""Squeeze angle maximising the QFI through ``spec`` at fixed :math:`\bar n`.

    Returns ``(theta_opt, qfi_opt, var_x_opt)``.  Without loss the answer is
    always ``theta = 0`` (maximum anti-squeezing of :math:`x`); with detection
    loss the optimum rotates away from it, and the optimal phase-space extent
    along :math:`x` becomes finite.
    """
    thetas = np.linspace(-0.5 * np.pi, 0.5 * np.pi, n_grid)
    qfis = np.array([gaussian_qfi_lambda(squeezed_vacuum_at_fixed_nbar(nbar, t), spec) for t in thetas])
    j = int(np.argmax(qfis))
    return float(thetas[j]), float(qfis[j]), float(squeezed_vacuum_at_fixed_nbar(nbar, thetas[j]).cov[0, 0])
