r"""Truncated Fock-space operators (dense complex ``numpy`` arrays).

All operators are built in the ``N``-dimensional truncated space; the
truncation error is controlled by :mod:`ligo_backaction.convergence`.
"""

from __future__ import annotations

from functools import lru_cache

import numpy as np
from scipy.linalg import expm
from scipy.special import gammaln

__all__ = [
    "annihilation",
    "number",
    "x_op",
    "p_op",
    "quad_op",
    "backaction_unitary",
    "signal_unitary",
    "joint_unitary",
    "rotation_unitary",
    "coherent_ket",
    "displace_op",
    "quad_eig",
    "squeeze_op",
    "as_density_matrix",
    "expect",
    "variance",
]


@lru_cache(maxsize=64)
def annihilation(N: int) -> np.ndarray:
    """Truncated annihilation operator of dimension ``N``."""
    return np.diag(np.sqrt(np.arange(1, N, dtype=float)), 1)


@lru_cache(maxsize=64)
def number(N: int) -> np.ndarray:
    return np.diag(np.arange(N, dtype=float)).astype(complex)


@lru_cache(maxsize=64)
def x_op(N: int) -> np.ndarray:
    r""":math:`\hat x = (a + a^\dagger)/\sqrt2`."""
    a = annihilation(N)
    return ((a + a.conj().T) / np.sqrt(2)).astype(complex)


@lru_cache(maxsize=64)
def p_op(N: int) -> np.ndarray:
    r""":math:`\hat p = (a - a^\dagger)/(i\sqrt2)`."""
    a = annihilation(N)
    return ((a - a.conj().T) / (1j * np.sqrt(2))).astype(complex)


@lru_cache(maxsize=128)
def quad_op(N: int, phi: float = 0.0) -> np.ndarray:
    r""":math:`\hat q_\varphi = \cos\varphi\,\hat x + \sin\varphi\,\hat p`."""
    if phi == 0.0:
        return x_op(N)
    return np.cos(phi) * x_op(N) + np.sin(phi) * p_op(N)


@lru_cache(maxsize=128)
def quad_eig(N: int, phi: float = 0.0):
    """Eigendecomposition of :math:`\hat q_\varphi`, cached per ``(N, phi)``.

    Every unitary generated by a function of a single quadrature -- the
    ponderomotive shear, the signal displacement, and their sum when they
    commute -- is diagonal in this basis.  Reusing the decomposition turns each
    such unitary into an O(N^2) construction instead of a dense matrix
    exponential, which matters a lot because the cutoffs needed at large kappa
    are large.
    """
    vals, vecs = np.linalg.eigh(quad_op(N, phi))
    return vals, vecs


def _from_quad_phase(N: int, phi: float, phase_fn) -> np.ndarray:
    vals, vecs = quad_eig(N, phi)
    return (vecs * phase_fn(vals)) @ vecs.conj().T


@lru_cache(maxsize=256)
def backaction_unitary(N: int, kappa: float) -> np.ndarray:
    r"""Radiation-pressure (ponderomotive) unitary :math:`e^{-i\kappa \hat x^2/2}`.

    In the Heisenberg picture this implements the shear
    :math:`x \to x,\ p \to p - \kappa x`, i.e. the linearised back-action of a
    free-mass interferometer at a single sideband frequency.
    """
    return _from_quad_phase(N, 0.0, lambda v: np.exp(-0.5j * float(kappa) * v**2))


@lru_cache(maxsize=256)
def signal_unitary(N: int, lam: float, phi: float = 0.0) -> np.ndarray:
    r"""Signal displacement :math:`e^{+i\lambda \hat q_\varphi}`.

    For ``phi = 0`` this shifts :math:`p \to p + \lambda`, the free-mass
    gravitational-wave signal.
    """
    return _from_quad_phase(N, phi, lambda v: np.exp(1j * float(lam) * v))


@lru_cache(maxsize=256)
def joint_unitary(N: int, kappa: float, lam: float, phi: float = 0.0) -> np.ndarray:
    r"""Simultaneous signal and back-action, :math:`e^{-i(\kappa \hat x^2/2 - \lambda \hat q_\varphi)}`.

    This is the "BA3" physical case in which the signal accumulates while
    radiation pressure acts.  For ``phi = 0`` the two generators commute and
    this factorises exactly into the BA1/BA2 orderings.
    """
    if np.sin(phi) == 0.0:
        sign = np.cos(phi)
        return _from_quad_phase(N, 0.0, lambda v: np.exp(-1j * (0.5 * float(kappa) * v**2 - sign * float(lam) * v)))
    x = x_op(N)
    gen = 0.5 * float(kappa) * (x @ x) - float(lam) * quad_op(N, phi)
    return expm(-1j * gen)


def rotation_unitary(N: int, theta: float) -> np.ndarray:
    r""":math:`e^{-i\theta \hat n}`."""
    return np.diag(np.exp(-1j * float(theta) * np.arange(N)))


@lru_cache(maxsize=256)
def displace_op(N: int, alpha: complex) -> np.ndarray:
    a = annihilation(N)
    return expm(alpha * a.conj().T - np.conj(alpha) * a)


def coherent_ket(N: int, alpha: complex) -> np.ndarray:
    r"""Coherent state by its analytic Fock amplitudes, renormalised on the cutoff.

    :math:`\langle n|\alpha\rangle = e^{-|\alpha|^2/2}\alpha^n/\sqrt{n!}`.  This
    avoids exponentiating a dense displacement operator, which matters inside
    the root-finding loops that pin a state's mean photon number.
    """
    n = np.arange(N)
    log_amp = -0.5 * abs(alpha) ** 2 + n * np.log(complex(alpha) if alpha != 0 else 1.0) - 0.5 * gammaln(n + 1.0)
    amp = np.exp(log_amp) if alpha != 0 else np.eye(1, N, 0)[0].astype(complex)
    amp = np.asarray(amp, dtype=complex)
    return amp / np.linalg.norm(amp)


@lru_cache(maxsize=256)
def squeeze_op(N: int, z: complex) -> np.ndarray:
    r""":math:`S(z) = \exp[\tfrac12(z^* a^2 - z a^{\dagger 2})]`.

    For real ``z = r > 0`` this squeezes :math:`x`
    (:math:`S^\dagger x S = e^{-r} x`).
    """
    a = annihilation(N)
    a2 = a @ a
    return expm(0.5 * (np.conj(z) * a2 - z * a2.conj().T))


def expect(op: np.ndarray, rho: np.ndarray) -> float:
    """Expectation value of a Hermitian operator in state ``rho`` (density matrix or ket)."""
    rho = as_density_matrix(rho)
    return float(np.real(np.trace(op @ rho)))


def variance(op: np.ndarray, rho: np.ndarray) -> float:
    rho = as_density_matrix(rho)
    m = expect(op, rho)
    return float(np.real(np.trace(op @ op @ rho))) - m**2


def as_density_matrix(state: np.ndarray) -> np.ndarray:
    """Accept either a ket (1-D) or a density matrix (2-D) and return a density matrix."""
    state = np.asarray(state)
    if state.ndim == 1:
        return np.outer(state, state.conj())
    return state
