"""
Verify the commutation structure of signal / back-action / noise ordering.

Claim under test
----------------
With the mentor's convention the GW signal is generated by x = a + a†
(S = exp(-i epsilon_p x), a phase-quadrature displacement) and radiation-pressure
back-action is B = exp(-i g x^2 t).  Since [x, x^2] = 0:

  1. S and B commute, so swapping them WHEREVER THEY ARE ADJACENT leaves the
     output state (and hence the QFI for epsilon_p) unchanged.
  2. This does NOT make the signal's position relative to LOSS irrelevant:
     loss D[a] commutes with neither S nor B, so moving S (or B) across the
     loss block changes the channel.

Prediction for the 6 orderings of {S, B, L}: they collapse into exactly
4 equivalence classes

    {S B L, B S L},  {L S B, L B S},  {S L B},  {B L S}

with within-class agreement at numerical precision and between-class
differences far above it.  Controls:

  * eta = 1 (no loss): all 6 orderings agree and equal 4 Var(x) of the
    probe, independent of kappa_ba  ("back-action is invisible without
    decoherence").
  * kappa_ba -> 0: orderings collapse to 2 classes (S before / after L).
  * Same 6-permutation table with dephasing D[n] in place of loss.
  * QFI cross-checked against the full SLD construction Tr[rho L^2].
  * N_basis convergence spot check.

Run:  python ordering-verification/verify_ordering.py
Writes results to ordering-verification/results/ (CSV + markdown summary).
"""

from __future__ import annotations

import itertools
from pathlib import Path

import numpy as np
import qutip as qt
from numpy.linalg import eigh

HERE = Path(__file__).resolve().parent
RESULTS = HERE / "results"

PREC_DIFF = 1e-5     # finite-difference step for d rho / d epsilon_p (the signal strength)
PREC_EIG = 1e-10     # eigenvalue threshold in the QFI sum
SOLVER_OPTS = {"atol": 1e-12, "rtol": 1e-12, "nsteps": 100_000}


# ---------------------------------------------------------------------------
# Channel blocks.  S and B are exact unitaries; L and D are Lindblad stages.
# ---------------------------------------------------------------------------

def _x_op(N):
    a = qt.destroy(N)
    return a + a.dag()


def block_signal(rho, epsilon_p, N):
    """S = exp(-i epsilon_p x): displacement generated by x (mentor's convention:
    the GW creates phase-quadrature fluctuations; x is the generator)."""
    U = (-1j * epsilon_p * _x_op(N)).expm()
    return U * rho * U.dag()


def block_backaction(rho, kappa_ba, N):
    """B = exp(-i g x^2), g = kappa_ba / 2 (ba_to_g with t = 1)."""
    g = kappa_ba / 2.0
    U = (-1j * g * _x_op(N) ** 2).expm()
    return U * rho * U.dag()


def block_loss(rho, eta, N):
    """Pure-loss channel of transmission eta via mesolve, D[sqrt(kappa) a]
    for t = 1 with kappa = -ln(eta)."""
    if eta >= 1.0:
        return rho
    a = qt.destroy(N)
    kappa = -np.log(eta)
    res = qt.mesolve(0 * a.dag() * a, rho, [0.0, 1.0],
                     [np.sqrt(kappa) * a], options=SOLVER_OPTS)
    return res.states[-1]


def block_dephase(rho, chi, N):
    """Dephasing channel D[sqrt(chi) n] for t = 1, applied exactly:
    rho_mn -> rho_mn exp(-chi (m-n)^2 / 2).  (mesolve is too stiff here --
    decay rates grow like chi N^2 -- and its integration error broke the
    S<->B swap invariance at the 1e-3 level before this exact map.)"""
    if chi <= 0.0:
        return rho
    m = np.arange(N)
    fac = np.exp(-chi * (m[:, None] - m[None, :]) ** 2 / 2.0)
    return qt.Qobj(rho.full() * fac)


def apply_ordering(rho0, ordering, epsilon_p, kappa_ba, noise_strength, N,
                   noise="loss"):
    """Apply blocks named by `ordering` (string over 'S','B','L') in order.
    'L' is loss (eta = noise_strength) or dephasing (chi = noise_strength)."""
    rho = rho0
    for ch in ordering:
        if ch == "S":
            rho = block_signal(rho, epsilon_p, N)
        elif ch == "B":
            rho = block_backaction(rho, kappa_ba, N)
        elif ch == "L":
            if noise == "loss":
                rho = block_loss(rho, noise_strength, N)
            else:
                rho = block_dephase(rho, noise_strength, N)
        else:
            raise ValueError(ch)
    return rho


# ---------------------------------------------------------------------------
# Exact Gaussian reference (valid for coherent / squeezed-vacuum probes).
#
# Units: x = a + a†, p = -i(a - a†), [x, p] = 2i, Var_vac = 1.  In these
# units B = exp(-i (kappa/2) x^2) shears p -> p - 2*kappa*x  (note the
# factor 2 relative to the naive reading of ba_to_g; a convention question
# to raise with the mentor, it rescales kappa but not the ordering physics).
# QFI for a parameter entering only the first moments: F = u^T V^{-1} u.
# ---------------------------------------------------------------------------

def gaussian_reference(kind, ordering, kappa_ba, eta, n_target=None):
    if n_target is None:
        n_target = N_TARGET
    if kind == "coherent":
        V = np.eye(2)
    elif kind == "sqz_vac":
        r = np.arcsinh(np.sqrt(n_target))
        V = np.diag([np.exp(2 * r), np.exp(-2 * r)])  # anti-squeezed x
    else:
        return None  # non-Gaussian probe
    u = np.zeros(2)
    for ch in ordering:
        if ch == "S":
            u = u + np.array([0.0, 2.0])  # exp(-i epsilon_p x): p -> p + 2 epsilon_p
        elif ch == "B":
            S = np.array([[1.0, 0.0], [-2.0 * kappa_ba, 1.0]])
            V = S @ V @ S.T
            u = S @ u
        elif ch == "L":
            V = eta * V + (1.0 - eta) * np.eye(2)
            u = np.sqrt(eta) * u
    return float(u @ np.linalg.solve(V, u))


# ---------------------------------------------------------------------------
# QFI (dense, eigendecomposition; mirrors quantum-sensing-py/sld.py)
# ---------------------------------------------------------------------------

def qfi_from_rhos(rho_plus, rho_minus, rho0, prec=PREC_DIFF):
    drho = (rho_plus.full() - rho_minus.full()) / (2 * prec)
    rho = rho0.full()
    evals, evecs = eigh(rho)
    drho_rot = evecs.conj().T @ drho @ evecs
    denom = evals[:, None] + evals[None, :]
    mask = np.abs(denom) > PREC_EIG
    qfi = np.sum(2.0 * np.abs(drho_rot[mask]) ** 2 / denom[mask])
    return float(np.real(qfi))


def qfi_via_sld(rho_plus, rho_minus, rho0, prec=PREC_DIFF):
    """Independent path: build the full SLD and return Tr[rho L^2]."""
    drho = (rho_plus.full() - rho_minus.full()) / (2 * prec)
    rho = rho0.full()
    evals, evecs = eigh(rho)
    drho_rot = evecs.conj().T @ drho @ evecs
    n = len(evals)
    L_rot = np.zeros((n, n), dtype=complex)
    for i in range(n):
        for j in range(n):
            denom = evals[i] + evals[j]
            if abs(denom) > PREC_EIG:
                L_rot[i, j] = 2.0 * drho_rot[i, j] / denom
    L = evecs @ L_rot @ evecs.conj().T
    L = (L + L.conj().T) / 2.0
    return float(np.real(np.trace(rho @ L @ L)))


def qfi_for_ordering(rho0, ordering, kappa_ba, noise_strength, N,
                     noise="loss", method="sum"):
    args = dict(kappa_ba=kappa_ba, noise_strength=noise_strength,
                N=N, noise=noise)
    rp = apply_ordering(rho0, ordering, +PREC_DIFF, **args)
    rm = apply_ordering(rho0, ordering, -PREC_DIFF, **args)
    rc = apply_ordering(rho0, ordering, 0.0, **args)
    if method == "sld":
        return qfi_via_sld(rp, rm, rc)
    return qfi_from_rhos(rp, rm, rc)


# ---------------------------------------------------------------------------
# Probe states at fixed mean photon number
# ---------------------------------------------------------------------------

def make_probe(kind, n_target, N):
    """Return a normalized ket with <n> = n_target (exact for coherent and
    squeezed; solved numerically for the cat)."""
    if kind == "coherent":
        psi = qt.coherent(N, np.sqrt(n_target))
    elif kind == "sqz_vac":
        # r < 0 anti-squeezes x = a + a†, the signal generator's conjugate
        # noise direction; sign only matters for the Var(x) benchmark value.
        r = np.arcsinh(np.sqrt(n_target))
        psi = qt.squeeze(N, -r) * qt.basis(N, 0)
    elif kind == "cat":
        # even cat |alpha> + |-alpha>:  <n> = alpha^2 tanh(alpha^2); solve.
        from scipy.optimize import brentq
        f = lambda al: al**2 * np.tanh(al**2) - n_target
        alpha = brentq(f, 1e-4, np.sqrt(n_target) + 2.0)
        psi = (qt.coherent(N, alpha) + qt.coherent(N, -alpha)).unit()
    else:
        raise ValueError(kind)
    return psi


def var_x(psi, N):
    x = _x_op(N)
    return float(qt.expect(x * x, psi) - qt.expect(x, psi) ** 2)


# ---------------------------------------------------------------------------
# The verification runs
# ---------------------------------------------------------------------------

ORDERINGS = ["".join(p) for p in itertools.permutations("SBL")]
# predicted equivalence classes
CLASSES = [("SBL", "BSL"), ("LSB", "LBS"), ("SLB",), ("BLS",)]

N_TARGET = 2.0
N_BASIS = 200


def run_table(kind, kappa_ba, noise_strength, noise, N=N_BASIS):
    rho0 = qt.ket2dm(make_probe(kind, N_TARGET, N))
    return {o: qfi_for_ordering(rho0, o, kappa_ba, noise_strength, N,
                                noise=noise) for o in ORDERINGS}


def class_report(tab):
    """Return (within-class max relative spreads, class representative values)."""
    spreads, reps = [], []
    for cls in CLASSES:
        vals = [tab[o] for o in cls]
        mean = np.mean(vals)
        spreads.append((max(vals) - min(vals)) / mean if mean else 0.0)
        reps.append(mean)
    return spreads, reps


def main():
    RESULTS.mkdir(exist_ok=True)
    rows = []
    lines = ["# Ordering verification results", ""]

    def log(s=""):
        print(s)
        lines.append(s)

    log(f"Probe <n> = {N_TARGET}, N_basis = {N_BASIS}, "
        f"finite-difference step {PREC_DIFF}")
    log()

    # ---- main 6-permutation tables --------------------------------------
    cases = []
    for kind in ("coherent", "sqz_vac", "cat"):
        for kappa_ba in (0.5, 1.0):
            for noise, strength in (("loss", 0.9), ("loss", 0.7),
                                    ("dephase", 0.1)):
                cases.append((kind, kappa_ba, noise, strength))

    for kind, kappa_ba, noise, strength in cases:
        tab = run_table(kind, kappa_ba, strength, noise)
        spreads, reps = class_report(tab)
        label = (f"{kind}, kappa_ba={kappa_ba}, "
                 f"{'eta' if noise == 'loss' else 'chi'}={strength}")
        log(f"## {label}")
        for o in ORDERINGS:
            g = (gaussian_reference(kind, o, kappa_ba, strength)
                 if noise == "loss" else None)
            gtxt = f"   exact(Gaussian) = {g:.10f}" if g is not None else ""
            rows.append(dict(state=kind, kappa_ba=kappa_ba, noise=noise,
                             strength=strength, ordering=o, qfi=tab[o],
                             qfi_exact_gaussian=g))
            log(f"    {o}: QFI = {tab[o]:.10f}{gtxt}")
        log(f"    within-class spreads "
            f"{{SBL,BSL}}={spreads[0]:.2e}  {{LSB,LBS}}={spreads[1]:.2e}")
        log(f"    class values: S,B-then-L={reps[0]:.6f}  "
            f"L-then-S,B={reps[1]:.6f}  SLB={reps[2]:.6f}  BLS={reps[3]:.6f}")
        ok = spreads[0] < 1e-7 and spreads[1] < 1e-7
        log(f"    adjacent S<->B swap invariant: {'PASS' if ok else 'FAIL'}")
        log()

    # ---- control 1: lossless, all orderings equal 4 Var(x) --------------
    log("## Control: eta = 1 (no decoherence)")
    for kind in ("coherent", "sqz_vac", "cat"):
        psi = make_probe(kind, N_TARGET, N_BASIS)
        rho0 = qt.ket2dm(psi)
        vx = var_x(psi, N_BASIS)
        vals = []
        for kappa_ba in (0.5, 1.0):
            tab = {o: qfi_for_ordering(rho0, o, kappa_ba, 1.0, N_BASIS)
                   for o in ORDERINGS}
            vals += list(tab.values())
        spread = (max(vals) - min(vals)) / np.mean(vals)
        dev = abs(np.mean(vals) - 4 * vx) / (4 * vx)
        ok = spread < 1e-7 and dev < 1e-4
        log(f"    {kind}: QFI = {np.mean(vals):.6f}, 4 Var(x) = {4*vx:.6f}, "
            f"spread over 12 (ordering, kappa) combos = {spread:.2e}, "
            f"deviation = {dev:.2e}  {'PASS' if ok else 'FAIL'}")
    log()

    # ---- control 2: kappa_ba -> 0 collapses to 2 classes ----------------
    log("## Control: kappa_ba = 0, eta = 0.8 (only S-vs-L position survives)")
    tab = run_table("sqz_vac", 0.0, 0.8, "loss")
    s_first = [tab[o] for o in ORDERINGS if o.index("S") < o.index("L")]
    l_first = [tab[o] for o in ORDERINGS if o.index("L") < o.index("S")]
    sp1 = (max(s_first) - min(s_first)) / np.mean(s_first)
    sp2 = (max(l_first) - min(l_first)) / np.mean(l_first)
    ok = sp1 < 1e-7 and sp2 < 1e-7
    log(f"    S-before-L class: {np.mean(s_first):.6f} (spread {sp1:.2e})")
    log(f"    L-before-S class: {np.mean(l_first):.6f} (spread {sp2:.2e})")
    log(f"    2-class collapse: {'PASS' if ok else 'FAIL'}")
    log()

    # ---- control 3: SLD cross-check -------------------------------------
    log("## Control: QFI direct sum vs Tr[rho L^2] (SLD path)")
    rho0 = qt.ket2dm(make_probe("sqz_vac", N_TARGET, N_BASIS))
    for o in ("SBL", "BLS"):
        q1 = qfi_for_ordering(rho0, o, 2.0, 0.7, N_BASIS, method="sum")
        q2 = qfi_for_ordering(rho0, o, 2.0, 0.7, N_BASIS, method="sld")
        dev = abs(q1 - q2) / q1
        log(f"    {o}: sum={q1:.8f}  sld={q2:.8f}  rel dev={dev:.2e}  "
            f"{'PASS' if dev < 1e-6 else 'FAIL'}")
    log()

    # ---- control 4: Fock truncation vs exact Gaussian -------------------
    log("## Control: Fock-basis truncation vs exact Gaussian reference")
    log("    (B inflates Var(p) by (2 kappa)^2 Var(x); large kappa needs a")
    log("    much larger basis than the probe's <n> suggests)")
    for kind, kappa_ba, o, N in (("coherent", 0.5, "BLS", N_BASIS),
                                 ("coherent", 1.0, "BLS", N_BASIS),
                                 ("sqz_vac", 0.5, "BLS", N_BASIS),
                                 ("sqz_vac", 1.0, "BLS", N_BASIS),
                                 ("sqz_vac", 2.0, "BLS", 60)):
        exact = gaussian_reference(kind, o, kappa_ba, 0.7)
        q = qfi_for_ordering(qt.ket2dm(make_probe(kind, N_TARGET, N)),
                             o, kappa_ba, 0.7, N)
        dev = abs(q - exact) / exact
        log(f"    {kind}, kappa={kappa_ba}, {o}: QFI(N={N}) = {q:.6f}, "
            f"exact = {exact:.6f}, rel dev = {dev:.2e}  "
            f"{'converged' if dev < 5e-3 else 'NOT CONVERGED'}")
    log("    Note: kappa_ba = 2 needs N ~ 700 for <1e-3 agreement (measured:")
    log("    N=300 -> 4.7e-2, N=500 -> 4.4e-3, N=700 -> 4.1e-4); the shear")
    log("    inflates Var(p) by (2 kappa)^2 Var(x), so basis demands grow fast.")
    log()

    # ---- write outputs ---------------------------------------------------
    import csv
    with open(RESULTS / "ordering_qfi.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    (RESULTS / "SUMMARY.md").write_text("\n".join(lines) + "\n")
    print(f"\nWrote {RESULTS/'ordering_qfi.csv'} and {RESULTS/'SUMMARY.md'}")


if __name__ == "__main__":
    main()
